package com.disasterrelief.service;

import java.util.List;
import com.disasterrelief.dto.*;
import com.disasterrelief.exception.NotFoundException;
import com.disasterrelief.model.*;
import com.disasterrelief.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
public class ReliefService {
 private final VolunteerRepository volunteers; private final ResourceRepository resources; private final ShelterRepository shelters; private final EmergencyRequestRepository requests; private final RequestHistoryRepository history;
 public ReliefService(VolunteerRepository v, ResourceRepository r, ShelterRepository s, EmergencyRequestRepository e, RequestHistoryRepository h){volunteers=v;resources=r;shelters=s;requests=e;history=h;}
 public List<Volunteer> volunteers(){return volunteers.findAll();} public Volunteer volunteer(Long id){return volunteers.findById(id).orElseThrow(()->new NotFoundException("Volunteer",id));}
 public Volunteer saveVolunteer(VolunteerRequest x, Long id){Volunteer v=id==null?new Volunteer():volunteer(id); if((id==null&&volunteers.existsByEmail(x.email()))||(id!=null&&volunteers.findByEmail(x.email()).filter(o->!o.getId().equals(id)).isPresent()))throw new IllegalArgumentException("Email is already registered");v.setFullName(x.fullName());v.setAge(x.age());v.setGender(x.gender());v.setPhone(x.phone());v.setEmail(x.email());v.setAddress(x.address());v.setSkills(x.skills());v.setAvailability(x.availability());v.setEmergencyContact(x.emergencyContact());return volunteers.save(v);} public void deleteVolunteer(Long id){volunteers.delete(volunteer(id));}
 public List<Resource> resources(){return resources.findAll();} public Resource resource(Long id){return resources.findById(id).orElseThrow(()->new NotFoundException("Resource",id));} public Resource saveResource(ResourceRequest x,Long id){Resource r=id==null?new Resource():resource(id);r.setName(x.name());r.setCategory(x.category());r.setQuantity(x.quantity());r.setUnit(x.unit());r.setLocation(x.location());r.setStatus(x.status());return resources.save(r);} public void deleteResource(Long id){resources.delete(resource(id));}
 public List<Shelter> shelters(){return shelters.findAll();} public Shelter shelter(Long id){return shelters.findById(id).orElseThrow(()->new NotFoundException("Shelter",id));} public Shelter saveShelter(ShelterRequest x,Long id){if(x.currentOccupancy()>x.capacity())throw new IllegalArgumentException("Current occupancy cannot exceed capacity");Shelter s=id==null?new Shelter():shelter(id);s.setName(x.name());s.setLocation(x.location());s.setCapacity(x.capacity());s.setCurrentOccupancy(x.currentOccupancy());s.setContactPerson(x.contactPerson());s.setContactNumber(x.contactNumber());s.setStatus(x.status());return shelters.save(s);} public void deleteShelter(Long id){shelters.delete(shelter(id));}
 public List<EmergencyRequest> requests(){return requests.findAll();} public EmergencyRequest request(Long id){return requests.findById(id).orElseThrow(()->new NotFoundException("Emergency request",id));} public EmergencyRequest saveRequest(EmergencyRequestPayload x,Long id){EmergencyRequest r=id==null?new EmergencyRequest():request(id);r.setRequesterName(x.requesterName());r.setContactNumber(x.contactNumber());r.setLocation(x.location());r.setRequestType(x.requestType());r.setDescription(x.description());r.setPriority(x.priority());r.setPeopleAffected(x.peopleAffected());r.setRequestDateTime(x.requestDateTime());r.setStatus(x.status());r=requests.save(r);if(id==null)history.save(new RequestHistory(r,x.status(),"Request created"));return r;} public EmergencyRequest updateStatus(Long id,StatusUpdateRequest x){EmergencyRequest r=request(id);r.setStatus(x.status());history.save(new RequestHistory(r,x.status(),x.note()));return r;} public List<RequestHistory> history(Long id){request(id);return history.findByRequestIdOrderByChangedAtAsc(id);} public void deleteRequest(Long id){EmergencyRequest r=request(id);history.findByRequestIdOrderByChangedAtAsc(id).forEach(history::delete);requests.delete(r);}
 public long volunteerCount(){return volunteers.count();} public long availableResources(){return resources.countByStatus(ResourceStatus.AVAILABLE);} public long activeShelters(){return shelters.countByStatus(ShelterStatus.ACTIVE);} public long pendingRequests(){return requests.countByStatus(RequestStatus.PENDING);} public long assignedRequests(){return requests.countByStatus(RequestStatus.ASSIGNED);} public long inProgressRequests(){return requests.countByStatus(RequestStatus.IN_PROGRESS);} public long resolvedRequests(){return requests.countByStatus(RequestStatus.RESOLVED);} public long totalShelterCapacity(){return shelters.totalCapacity();} public long currentShelterOccupancy(){return shelters.totalOccupancy();}
}
